name: Flake Check

on: 
  workflow_run:
    workflows: ["Flake Update"]
    types:
      - completed
  push:
    branches:
      - main

jobs:
  flake-check:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install Nix
      uses: cachix/install-nix-action@v26
      with: 
        nix_path: nixpkgs=channel:nixos-unstable
    
    - name: Version
      run: |
        nix --version
        nix-env --version
    - name: Flake check
      run: nix flake check   
