name: Flake Update

on: 
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install Nix
      uses: cachix/install-nix-action@v23
      with: 
        nix_path: nixpkgs=channel:nixos-unstable

    - name: Flake update
      run: nix flake update

    - name: Readme.py
      run: nix run github:erictossell/readme-py -- -a erictossell -d -l -fs -fi -hmd docs/readme.md 

    - name: Commit and push
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: "Flake update"
